In [10]:
import torch
import torch.nn as nn

In [11]:
# to print results without scientific notations.
torch.set_printoptions(sci_mode=False)

In [17]:
class LayerNormalization(nn.Module):
    def __init__(self, emb_dim):
        super().__init__()
        self.esp = 1e-5
        self.scale = nn.Parameter(torch.ones(emb_dim))
        self.shift = nn.Parameter(torch.zeros(emb_dim))


    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = x.var(dim=-1, keepdim=True, unbiased=False)
        norm_x = (x - mean) / torch.sqrt(var + self.esp)
        return self.scale * norm_x + self.shift

In [18]:
# This specific implementation of layer Normalization operates on the last dimension of the
# input tensor x, which represents the embedding dimension (emb_dim). The variable eps is a
# small constant (epsilon) added to the variance to prevent division by zero during
# normalization. The scale and shift are two trainable parameters (of the same dimension
# as the input) that the LLM automatically adjusts during training if it is determined that
# doing so would improve the model's performance on its training task. This allows the model
# to learn appropriate scaling and shifting that best suit the data it is processing.

In [19]:
torch.manual_seed(123)
batch_example = torch.randn(2, 5)
print(batch_example)

tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969],
        [ 0.2093, -0.9724, -0.7550,  0.3239, -0.1085]])


In [20]:
# testing out class is it working correctly
ln = LayerNormalization(5)
out_ln = ln(batch_example)
mean = torch.mean(out_ln, dim=-1, keepdim=True)
var = torch.var(out_ln, dim=-1, keepdim=True)
print(mean)
print(var)

tensor([[    -0.0000],
        [     0.0000]], grad_fn=<MeanBackward1>)
tensor([[1.2499],
        [1.2500]], grad_fn=<VarBackward0>)
